#!/usr/bin/env python3
"""
spec_traceability_check.py — Claude Code PostToolUse hook

src/ や tests/ 配下の新規/編集ファイルに `@spec <ID>` トレーサビリティタグが含まれているか確認する。
タグが無い場合は警告(デフォルト) または ブロック (IMPL_STRICT_TRACEABILITY=1)。

IMPL_RULES R-2 に対応。

判定対象:
- src/, tests/ 配下
- 拡張子: .py, .ts, .tsx, .js, .jsx, .vue, .svelte

判定対象外:
- 自動生成ファイル(`# generated by ...` / `// @generated` を含む)
- `__init__.py`, `index.ts` などのエントリポイント空ファイル相当
- 設定ファイル(*.config.* / *.cjs / *.mjs)
"""
from __future__ import annotations
import json
import os
import re
import sys

SPEC_TAG = re.compile(r"@spec\b")
SPEC_ID = re.compile(r"\b[A-Z]{1,3}-\d{2,4}\b")

GENERATED_MARKERS = ("# generated by ", "// @generated", "# @generated", "// THIS FILE IS AUTOGENERATED")

# 中身がほぼ空のファイルは対象外
TRIVIAL_THRESHOLD = 40  # 文字数(コメント・空白除く)


def _extract_payload(data: dict) -> tuple[str, str]:
    ti = data.get("tool_input", {}) or {}
    fp = ti.get("file_path") or ti.get("path") or ""
    content = ti.get("content") or ti.get("new_string") or ti.get("text") or ""
    if "edits" in ti and isinstance(ti["edits"], list):
        content = "\n".join((e.get("new_string") or "") for e in ti["edits"])
    return fp, content


def _normalize(p: str) -> str:
    return p.replace("\\", "/")


def _in_scope(fp: str) -> bool:
    f = _normalize(fp)
    if "/src/" not in f and "/tests/" not in f and not f.endswith((
        # ルートが src/tests のケース
    )):
        # 念のためサフィックス末端比較
        parts = f.split("/")
        if not any(p in {"src", "tests"} for p in parts):
            return False
    # 拡張子
    if not f.endswith((".py", ".ts", ".tsx", ".js", ".jsx", ".vue", ".svelte")):
        return False
    # 設定ファイル
    base = f.rsplit("/", 1)[-1]
    if base in {"__init__.py", "index.ts", "index.tsx", "index.js", "index.jsx"}:
        # 空に近いインデックスファイルは対象外
        return False
    if ".config." in base or base.endswith((".cjs", ".mjs", ".d.ts")):
        return False
    return True


def _is_trivial(content: str) -> bool:
    # コメント・空行を除いた文字数で判定
    no_comment = re.sub(r"(?m)^\s*(#|//).*$", "", content)
    no_blank = re.sub(r"\s+", "", no_comment)
    return len(no_blank) < TRIVIAL_THRESHOLD


def _is_generated(content: str) -> bool:
    head = content[:1024]
    return any(m in head for m in GENERATED_MARKERS)


def has_spec_tag(content: str) -> tuple[bool, str | None]:
    if not SPEC_TAG.search(content):
        return False, None
    # @spec の近傍に ID が居るか
    for m in SPEC_TAG.finditer(content):
        window = content[m.start(): m.start() + 200]
        id_match = SPEC_ID.search(window)
        if id_match:
            return True, id_match.group(0)
    return False, None


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0

    tool = data.get("tool_name", "")
    if tool not in {"Write", "Edit", "MultiEdit"}:
        return 0

    fp, content = _extract_payload(data)
    if not fp or not content:
        return 0

    if not _in_scope(fp):
        return 0
    if _is_generated(content) or _is_trivial(content):
        return 0

    ok, sample_id = has_spec_tag(content)
    if ok:
        return 0

    # 警告 or ブロック
    strict = os.environ.get("IMPL_STRICT_TRACEABILITY", "0") == "1"
    print("[spec_traceability_check] @spec タグが見つかりません。", file=sys.stderr)
    print(f"  対象: {fp}", file=sys.stderr)
    print(
        "  対応: ファイル冒頭の docstring/コメントに `@spec F-XXX` のように仕様 ID を記載してください。",
        file=sys.stderr,
    )
    print("  例 (Python): \"\"\"@spec F-014 — フォローコメント記録\"\"\"", file=sys.stderr)
    print("  例 (TS):     /** @spec EP-042 */", file=sys.stderr)
    print("  ルール: references/IMPL_RULES.md R-2 (トレーサビリティ)", file=sys.stderr)
    return 2 if strict else 1


if __name__ == "__main__":
    sys.exit(main())
